open_cnil:
  outputs:
    dev:
      dataset: dbt
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /usr/local/airflow/include/dbt/open_cnil/service_account/cnil-392113-4bf35dbd3bd9.json
      location: EU
      method: service-account
      priority: interactive
      project: cnil-392113
      threads: 1
      type: bigquery
  target: dev
