{% macro clean_sect_controles(secteur)%}
CASE
        WHEN {{secteur}} IN ('Énergie', 'Energie') THEN 'Énergie'
        WHEN {{secteur}} IN ('Éducation', 'Education', 'Education/culture/sport') THEN 'Éducation'
        WHEN {{secteur}} IN ('Vote électronique') THEN 'Technologie'
        WHEN {{secteur}} IN ('Télécommunications') THEN 'Télécommunications'
        WHEN {{secteur}} IN ('Travail') THEN 'Emploi'
        WHEN {{secteur}} IN ('Transports', 'Transport') THEN 'Transports'
        WHEN {{secteur}} IN ('Tourisme') THEN 'Tourisme'
        WHEN {{secteur}} IN ('Statistiques et enquêtes publiques') THEN 'Statistiques'
        WHEN {{secteur}} IN ('Sport') THEN 'Sport'
        WHEN {{secteur}} IN ('Social', 'Santé/social', 'Santé/ social', 'Santé ', 'Santé', 'Santé/social') THEN 'Santé/Social'
        WHEN {{secteur}} IN ('Régalien', 'Politique', 'Police/justice/sécurité', 'Police/ justice/ sécurité') THEN 'Régalien'
        WHEN {{secteur}} IN ('Presse') THEN 'Presse'
        WHEN {{secteur}} IN ('Particulier') THEN 'Particulier'
        WHEN {{secteur}} IN ('Nouvelles technologies') THEN 'Technologie'
        WHEN {{secteur}} IN ('Ministères') THEN 'Gouvernement'
        WHEN {{secteur}} IN ('Jeux') THEN 'Loisirs'
        WHEN {{secteur}} IN ('Immobilier') THEN 'Immobilier'
        WHEN {{secteur}} IN ('Finances publiques', 'Banques-Finance', 'Banques', 'Banque') THEN 'Finances'
        WHEN {{secteur}} IN ('Environnement') THEN 'Environnement'
        WHEN {{secteur}} IN ('Economie') THEN 'Économie'
        WHEN {{secteur}} IN ('Culture') THEN 'Culture'
        WHEN {{secteur}} IN ('Commerce') THEN 'Commerce'
        WHEN {{secteur}} IN ('Collectivités territoriales', 'Collectivités locales') THEN 'Collectivités'
        WHEN {{secteur}} IN ('Associatif', 'Activités politiques') THEN 'Associations'
        WHEN {{secteur}} IN ('Assurance', 'Assurances') THEN 'Assurance'
        ELSE 'Autre'
    END
{% endmacro %}